<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\DropdownField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class SliderButton extends DataObject
    {
        private static $default_sort = 'Sort';

        private static $singular_name = "Slider Button";
        private static $plural_name   = "Slider Buttons";

        private static $db = [
            'Name'     => 'Varchar',
            'Archived' => 'Boolean',
            'Sort'     => 'Int'
        ];

        private static $has_one = [
            'Image' => Image::class,
            'HomePage' => HomePage::class,
            'SliderContent' => SliderContent::class
        ];

        private static $owns = [
            'Image'
        ];

        private static $summary_fields = [
            'Name',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('HomePageID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('HomePageRO', 'Page', $this->HomePage()->Title));
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', UploadField::create('Image')->setFolderName('Navigation_Images'));
            $fields->addFieldToTab('Root.Main', DropdownField::create('SliderContentID', 'Slider content',
                SliderContent::get()->filter('Archived', false)->map('ID', 'Name')));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));

            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
