<?php

namespace {

    use SilverStripe\AssetAdmin\Forms\UploadField;
    use SilverStripe\Assets\File;
    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\CheckboxField;
    use SilverStripe\Forms\HiddenField;
    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Forms\TextareaField;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\DataObject;

    class VideoTab extends DataObject
    {
        private static $default_sort = 'Sort';

        private static $singular_name = "Video Tab";
        private static $plural_name   = "Video Tabs";

        private static $db = [
            'Name'        => 'Varchar',
            'VideoLink'   => 'Text',
            'Archived'    => 'Boolean',
            'Sort'        => 'Int'
        ];

        private static $has_one = [
            'Parent'=> SliderContent::class,
            'Video' => File::class,
            'VideoThumbnail' => Image::class
        ];

        private static $owns = [
            'Video',
            'VideoThumbnail'
        ];

        private static $summary_fields = [
            'Name',
            'Status'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
            $fields->removeByName('ParentID');
            $fields->addFieldToTab('Root.Main', ReadonlyField::create('ParentIDRO', 'Parent', $this->Parent()->Name));
            $fields->addFieldToTab('Root.Main', TextField::create('Name'));
            $fields->addFieldToTab('Root.Main', UploadField::create('Video')->setFolderName('Videos'));
            $fields->addFieldToTab('Root.Main', UploadField::create('VideoThumbnail')->setFolderName('Videos/Thumbnails'));
            $fields->addFieldToTab('Root.Main', TextareaField::create('VideoLink')->setDescription('External video link. e.g Vimeo or Youtube'));
            $fields->addFieldToTab('Root.Main', CheckboxField::create('Archived'));
            $fields->addFieldToTab('Root.Main', HiddenField::create('Sort'));
            return $fields;
        }

        public function getStatus()
        {
            if($this->Archived == 1) return _t('GridField.Archived', 'Archived');
            return _t('GridField.Live', 'Live');
        }
    }
}
